//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKmotors.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Client_Id { get; set; }
        public string Client_Name { get; set; }
        public string Client_Address { get; set; }
        public Nullable<System.DateTime> Client_DOB { get; set; }
        public Nullable<int> Client_Age { get; set; }
        public Nullable<int> Client_TP { get; set; }
    }
}
